import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  allSidebar: [{ type: 'autogenerated', dirName: '.' }],

  jotSidebar: [{ type: 'autogenerated', dirName: 'jot' }],

  oiSidebar: [{ type: 'autogenerated', dirName: 'oi' }],
  nativeStacksSidebar: [{ type: 'autogenerated', dirName: 'native-stacks' }],
  webStacksSidebar: [{ type: 'autogenerated', dirName: 'web-stacks' }],

  mathStacksSidebar: [{ type: 'autogenerated', dirName: 'math' }],
};

export default sidebars;
