import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a  from the docs folder structure
  all: [{ type: 'autogenerated', dirName: '.' }],

  jot: [{ type: 'autogenerated', dirName: 'jot' }],

  oi: [{ type: 'autogenerated', dirName: 'oi' }],
  se: [{ type: 'autogenerated', dirName: 'se' }],

  math: [{ type: 'autogenerated', dirName: 'math' }],
  english: [{ type: 'autogenerated', dirName: 'english' }],
  chemistry: [{ type: 'autogenerated', dirName: 'chemistry' }],

  moe: [{ type: 'autogenerated', dirName: 'moe' }],
  music: [{ type: 'autogenerated', dirName: 'music' }],
};

export default sidebars;
